# Generated by Django 5.1.3 on 2024-12-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={},
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
